- .gitattributes
> chore: add .gitattributes (fix #9)

- .circleci/config.yml
- .github/ISSUE_TEMPLATE/bug_report.md
- Dockerfile
- go.mod
> chore: bump go1.13

- .editorconfig
- .github/CODE_OF_CONDUCT.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- rules.mk
> chore: bumpdeps + fix eclint

- .circleci/config.yml
> chore: bump build deps

- .github/workflows/release.yml
- .releaserc.js
> feat: semantic release

- .circleci/config.yml
> feat: bump moul/build

- main.go
- main_test.go
> chore: less code in main

- .github/workflows/ci.yml
> feat: docker build on github actions

- .github/workflows/ci.yml
> feat: gh-actions go

- .github/workflows/ci.yml
> chore: bump golangci-lint github action

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .goreleaser.yml
> feat: configure semantic-release and goreleaser together

- .github/workflows/ci.yml
> feat: codecov github action

- .github/workflows/release.yml
> feat: auto godoc workflow

- .github/workflows/ci.yml
> feat: check gomod on CI

- .github/workflows/ci.yml
- main_test.go
> feat: check go.mod and go.sum in CI

- .github/workflows/ci.yml
- .gitignore
- rules.mk
Depends on https://github.com/report-ci/scripts/issues/17
> feat: add report-ci

- .github/workflows/pr.yml
> feat: set up release-note-preview github action

- .github/workflows/go.yml
> feat: only run go-related CI stuff when go changes

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/custom.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/SUPPORT.md
> feat: configure more .github stuff

- .github/workflows/go.yml
- .github/workflows/release.yml
- Dockerfile
> chore: go1.15

- .github/workflows/go.yml
- .github/workflows/release.yml
- Dockerfile
> chore: bump go1.15.1

- main.go
> fix: add missing rand.Seed call

- .github/workflows/go.yml
- .golangci.yml
- rules.mk
> feat: setup gci for deterministic imports fmt

- .golangci.yml
> feat: enable more linters by default

- go.mod
- go.sum
- main.go
> fix: bump zapconfig

- .github/workflows/pr.yml
> chore: disable pull_request_target on pr

- .github/workflows/go.yml
- .github/workflows/release.yml
> chore(ci): bump golangci-lint-action + use 1.15.x version format

- .github/workflows/docker.yml
- .github/workflows/go.yml
> feat: add Docker GitHub actions

- .gitattributes
> chore: reduce merge conflicts on sum files

- .github/workflows/debug.yml
> chore: add debug workflow

- README.md
> chore: run 'make generate' to check new CI triggers

- .gitpod.yml
- README.md
> feat: add gitpod

- .github/workflows/go.yml
- README.md
- go.sum
> chore: test against go1.16

- .github/workflows/go.yml
> chore: bump golangci-lint@v1.38

- .github/workflows/docker.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
> chore: refactor github actions to use matrix and better caching paths

- .goreleaser.yml
- tool/lint/Makefile
> chore: fix Makefile syntax

- .gitignore
> chore: add ignore for .idea in .gitignore config

- .github/workflows/docker.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
- .releaserc.js
- README.md
> chore: configure main branch

- .github/workflows/pr.yml
- .releaserc.js
- package.json
> chore: update semantic-release config

- .pre-commit-config.yaml
- README.md
> chore: add pre-commit script

- .github/workflows/docker.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
> feat: optimize CI with repoman

- README.md
CONTRIBUTING.md links to a 404 page.
> chore: fix CONTRIBUTING.md broken link

- .gitignore
> chore: gitignore .history/

- .github/workflows/scorecards.yml
> chore: do not fail if missing action's secret

- .github/workflows/label-sponsors.yml
> chore: fix is-sponsor-label

- .github/workflows/bearer.yml
> feat: add bearer

- .github/workflows/go.yml
> chore: update ci's golang version

- .github/workflows/go.yml
- .github/workflows/release.yml
- go.mod
- go.sum
Signed-off-by: Manfred Touron <94029+moul@users.noreply.github.com>
> chore: bump go1.19

- .github/workflows/pr.yml
- tool/lint/.markdownlint.json
> fix: markdown CI

- .github/workflows/go.yml
- .github/workflows/release.yml
- Dockerfile
- go.mod
Signed-off-by: Manfred Touron <94029+moul@users.noreply.github.com>
> chore: switch to go1.20
